### ISSUE TITLE
多张图片合成的时候怎么加上动画呢

### ISSUE THREAD

**Issue by zhoupIT** [ismilesky/MaxVideo#1]

**Comment by ismilesky** [comment]
加上什么动画？ 你的意思是合成时间过长，加的loading吗

**Comment by zhoupIT** [comment]
就是转场动画,图片与图片之间有个过渡.像汇声汇影一样

**Comment by ismilesky** [comment]
不是太明白你的需求，你是要在两张图片之间再加些东西吗？

**Comment by ismilesky** [comment]
不是太明白你的需求，你是要在两张图片之间再加些东西吗？

**Comment by ismilesky** [comment]
不是太明白你的需求，你是要在两张图片之间再加些东西吗？

**Comment by ismilesky** [comment]
不是太明白你的需求，你是要在两张图片之间再加些东西吗？

**Comment by ismilesky** [comment]
不是太明白你的需求，你是要在两张图片之间再加些东西吗？

**Comment by ismilesky** [comment]
不是太明白你的需求，你是要在两张图片之间再加些东西吗？

**Comment by ismilesky** [comment]
不是太明白你的需求，你是要在两张图片之间再加些东西吗？

**Comment by ismilesky** [comment]
不是太明白你的需求，你是要在两张图片之间再加些东西吗？

**Comment by ismilesky** [comment]
不是太清楚你的需求，是需要在每两张图片之间加些东西吗

**Comment by zhoupIT** [comment]
是的,像这样合成后视频 播放的时候,一张图片消失后 再出现一张,没有动画过渡,一般的视频不都是动画出现的图片吗,渐入渐出 飞入之类的

**Comment by ismilesky** [comment]
这种效果我也没做过， 我有个想法你看看行不行， 就是你把动画效果弄成帧图片， 把这些动效图片，插入到你想有这种效果的图片之间， 最后合成视频
