### ISSUE TITLE
多个不同方向的视频合成导出

### ISSUE THREAD

**Issue by RebornTai** [ismilesky/MaxVideo#5]
多个不同方向的视频合成后，导出到本地相册，方向不一致。 
请教一下，如何控制每个视频的方向呢？是在循环里设置吗？

**Comment by ismilesky** [comment]
有没有试过， 这个注释掉的方法呢？ ` /**
     // 视频的方向, 根据视频的方向同步视频轨道方向, 可根据需求自行调整
     CGAffineTransform videoTransform = assetVideoTrack.preferredTransform;
     if (videoTransform.a == 0 && videoTransform.b == 1.0 && videoTransform.c == -1.0 && videoTransform.d == 0) {
     NSLog(@"垂直拍摄");
     videoTransform = CGAffineTransformMakeRotation(M_PI_2);
     }else if (videoTransform.a == 0 && videoTransform.b == -1.0 && videoTransform.c == 1.0 && videoTransform.d == 0) {
     NSLog(@"倒立拍摄");
     videoTransform = CGAffineTransformMakeRotation(-M_PI_2);
     }else if (videoTransform.a == 1.0 && videoTransform.b == 0 && videoTransform.c == 0 && videoTransform.d == 1.0) {
     NSLog(@"Home键右侧水平拍摄");
     videoTransform = CGAffineTransformMakeRotation(0);
     }else if (videoTransform.a == -1.0 && videoTransform.b == 0 && videoTransform.c == 0 && videoTransform.d == -1.0) {
     NSLog(@"Home键左侧水平拍摄");
     videoTransform = CGAffineTransformMakeRotation(M_PI);
     }
     // 根据视频的方向同步视频轨道方向
     videoTrack.preferredTransform = videoTransform;
     */`
